import configparser

def config_Update_DTC_data(Data):
	write_config = configparser.ConfigParser()
	section = "DTC"
	write_config.add_section(section)
	write_config.set(section,"DTC_1" , Data[0])
	write_config.set(section,"DTC_2" , Data[1])
	write_config.set(section,"DTC_3", Data[2])
	write_config.set(section,"DTC_4", Data[3])
	write_config.set(section,"DTC_5", Data[4])
	write_config.set(section,"DTC_6", Data[5])
	write_config.set(section,"DTC_7", Data[6])
	write_config.set(section,"DTC_8", Data[7])
	write_config.set(section,"DTC_9", Data[8])
	write_config.set(section,"DTC_10", Data[9])
	write_config.set(section,"DTC_11", Data[10])
	write_config.set(section,"DTC_12", Data[11])
	write_config.set(section,"DTC_13", Data[12])
	write_config.set(section,"DTC_14", Data[13])
	write_config.set(section,"DTC_15", Data[14])
	write_config.set(section,"DTC_16", Data[15])
	write_config.set(section,"DTC_17", Data[16])
	write_config.set(section,"DTC_18", Data[17])
	write_config.set(section,"DTC_19", Data[18])
	write_config.set(section,"DTC_20", Data[19])
	write_config.set(section,"DTC_21", Data[20])
	write_config.set(section,"DTC_22", Data[21])
	write_config.set(section,"DTC_23", Data[22])
	write_config.set(section,"DTC_24", Data[23])
	write_config.set(section,"DTC_25", Data[24])
	write_config.set(section,"DTC_26", Data[25])
	write_config.set(section,"DTC_27", Data[26])
	write_config.set(section,"DTC_28", Data[27])
	write_config.set(section,"DTC_29", Data[28])
	write_config.set(section,"DTC_30", Data[29])
	write_config.set(section,"DTC_31", Data[30])
	write_config.set(section,"DTC_32", Data[31])
	write_config.set(section,"DTC_33", Data[32])
	write_config.set(section,"DTC_34", Data[33])
	write_config.set(section,"DTC_35", Data[34])
	write_config.set(section,"DTC_36", Data[35])
	write_config.set(section,"DTC_37", Data[36])
	write_config.set(section,"DTC_38", Data[37])
	write_config.set(section, "DTC_39", Data[38])
	cfgfile = open("DTC_Config.ini", 'w')
	write_config.write(cfgfile)
	cfgfile.close()


def read_DTC_Config():
	data_List = []
	section = "DTC"
	read_config = configparser.ConfigParser()
	read_config.read("DTC_Config.ini")
	data_List.append(read_config.get(section, "DTC_1"))
	data_List.append(read_config.get(section, "DTC_2"))
	data_List.append(read_config.get(section, "DTC_3"))
	data_List.append(read_config.get(section, "DTC_4"))
	data_List.append(read_config.get(section, "DTC_5"))
	data_List.append(read_config.get(section, "DTC_6"))
	data_List.append(read_config.get(section, "DTC_7"))
	data_List.append(read_config.get(section, "DTC_8"))
	data_List.append(read_config.get(section, "DTC_9"))
	data_List.append(read_config.get(section, "DTC_10"))
	data_List.append(read_config.get(section, "DTC_11"))
	data_List.append(read_config.get(section, "DTC_12"))
	data_List.append(read_config.get(section, "DTC_13"))
	data_List.append(read_config.get(section, "DTC_14"))
	data_List.append(read_config.get(section, "DTC_15"))
	data_List.append(read_config.get(section, "DTC_16"))
	data_List.append(read_config.get(section, "DTC_17"))
	data_List.append(read_config.get(section, "DTC_18"))
	data_List.append(read_config.get(section, "DTC_19"))
	data_List.append(read_config.get(section, "DTC_20"))
	data_List.append(read_config.get(section, "DTC_21"))
	data_List.append(read_config.get(section, "DTC_22"))
	data_List.append(read_config.get(section, "DTC_23"))
	data_List.append(read_config.get(section, "DTC_24"))
	data_List.append(read_config.get(section, "DTC_25"))
	data_List.append(read_config.get(section, "DTC_26"))
	data_List.append(read_config.get(section, "DTC_27"))
	data_List.append(read_config.get(section, "DTC_28"))
	data_List.append(read_config.get(section, "DTC_29"))
	data_List.append(read_config.get(section, "DTC_30"))
	data_List.append(read_config.get(section, "DTC_31"))
	data_List.append(read_config.get(section, "DTC_32"))
	data_List.append(read_config.get(section, "DTC_33"))
	data_List.append(read_config.get(section, "DTC_34"))
	data_List.append(read_config.get(section, "DTC_35"))
	data_List.append(read_config.get(section, "DTC_36"))
	data_List.append(read_config.get(section, "DTC_37"))
	data_List.append(read_config.get(section, "DTC_38"))
	data_List.append(read_config.get(section, "DTC_39"))
	return data_List
